"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, BookOpen, ChefHat, Clock, Play, Users } from "lucide-react";
import { createClientBrowser } from "@/lib/supabase";
import { Class } from "@/types";
import { formatDate, formatCurrency } from "@/lib/utils";

export default function HomePage() {
  const [classes, setClasses] = useState<Class[]>([]);
  const supabase = createClientBrowser();
  useEffect(() => { supabase.from("classes").select("*").eq("is_published", true).is("archived_at", null).order("class_date", { ascending: true }).limit(3).then(({ data }) => setClasses(data || [])); }, []);

  return <main>
    <section className="relative overflow-hidden bg-chef-dark text-white"><div className="absolute inset-0 bg-[url('/images/zimbabwean-chef-hero.png')] bg-cover bg-center opacity-20" /><div className="relative mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-32"><div className="max-w-3xl"><p className="mb-5 text-sm font-semibold uppercase tracking-[0.2em] text-brand-300">Live cooking, Zimbabwean soul</p><h1 className="text-balance text-4xl font-bold leading-tight sm:text-5xl lg:text-6xl">Master the art of <span className="text-brand-400">Zimbabwean cooking.</span></h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-gray-300">Join live masterclasses with Chipo, learn practical recipes, and build confidence in your kitchen.</p><div className="mt-8 flex flex-col gap-4 sm:flex-row"><Link href="/classes" className="inline-flex items-center justify-center gap-2 rounded-xl bg-brand-500 px-8 py-4 text-lg font-semibold hover:bg-brand-600">Browse classes <ArrowRight className="size-5" /></Link><Link href="/auth" className="inline-flex items-center justify-center gap-2 rounded-xl bg-white/10 px-8 py-4 text-lg font-semibold hover:bg-white/20"><Play className="size-5" /> Create free account</Link></div></div></div></section>
    <section className="border-b border-gray-100 bg-white"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-6 px-4 py-8 text-center md:grid-cols-4 sm:px-6 lg:px-8"><div><strong className="text-3xl text-brand-600">472K+</strong><p className="mt-1 text-sm text-gray-500">Facebook followers</p></div><div><strong className="text-3xl text-brand-600">7,000+</strong><p className="mt-1 text-sm text-gray-500">Students trained</p></div><div><strong className="text-3xl text-brand-600">50+</strong><p className="mt-1 text-sm text-gray-500">Classes hosted</p></div><div><strong className="text-3xl text-brand-600">Live</strong><p className="mt-1 text-sm text-gray-500">Interactive learning</p></div></div></section>
    <section className="py-16 sm:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-10 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-sm font-semibold uppercase tracking-[0.18em] text-brand-600">Published classes</p><h2 className="text-3xl font-bold text-gray-900 sm:text-4xl">Upcoming classes</h2><p className="mt-2 text-gray-600">Choose your next kitchen adventure.</p></div><Link href="/previous-classes" className="text-sm font-semibold text-brand-600 hover:text-brand-700">View previous classes <ArrowRight className="ml-1 inline size-4" /></Link></div>{classes.length === 0 ? <div className="rounded-2xl border border-dashed border-gray-300 py-16 text-center"><BookOpen className="mx-auto mb-3 size-10 text-gray-300" /><p className="font-semibold text-gray-900">New classes are being prepared</p><p className="mt-1 text-sm text-gray-500">Create an account to hear when registration opens.</p></div> : <div className="grid gap-6 md:grid-cols-3">{classes.map((cls) => <article key={cls.id} className="overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm transition-shadow hover:shadow-lg"><div className="flex h-40 items-center justify-center bg-gradient-to-br from-brand-100 to-brand-200 text-6xl">🍳</div><div className="flex flex-col gap-4 p-5"><div className="flex items-start justify-between gap-3"><h3 className="text-lg font-bold text-gray-900">{cls.title}</h3><span className="shrink-0 font-bold text-brand-600">{formatCurrency(cls.price, cls.currency)}</span></div><p className="line-clamp-2 text-sm leading-relaxed text-gray-600">{cls.description}</p><div className="flex flex-col gap-2 text-sm text-gray-500"><span className="flex items-center gap-2"><Clock className="size-4 text-brand-500" />{formatDate(cls.class_date)}</span><span className="flex items-center gap-2"><Users className="size-4 text-brand-500" />Max {cls.max_students} students</span></div>{cls.join_enabled ? <Link href={cls.share_slug ? `/class/${cls.share_slug}` : `/register?class=${cls.id}`} className="inline-flex items-center justify-center gap-2 rounded-xl bg-gray-900 py-3 font-semibold text-white hover:bg-brand-500">Join class <ArrowRight className="size-4" /></Link> : <span className="inline-flex cursor-not-allowed items-center justify-center rounded-xl bg-gray-100 py-3 font-semibold text-gray-400">Registration opening soon</span>}</div></article>)}</div>}</div></section>
    <section className="bg-brand-500 py-16 text-center text-white"><div className="mx-auto max-w-3xl px-4"><ChefHat className="mx-auto mb-4 size-10" /><h2 className="text-3xl font-bold sm:text-4xl">Keep learning with Chipo</h2><p className="mx-auto mt-4 max-w-xl text-lg text-brand-100">Create your free account and be first to know when a new class is published.</p><Link href="/auth" className="mt-8 inline-flex rounded-xl bg-white px-8 py-4 font-bold text-brand-600 hover:bg-gray-100">Create free account</Link></div></section>
  </main>;
}
